<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // A mini-assessment generated by the AI for a topic.
        Schema::create('assessments', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->foreignId('topic_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('chat_session_id')->nullable()->constrained()->nullOnDelete();
            $table->string('topic_name');
            $table->enum('status', ['pending', 'completed'])->default('pending');
            $table->unsignedTinyInteger('score')->nullable();      // correct count
            $table->unsignedTinyInteger('total')->default(0);      // question count
            $table->timestamp('completed_at')->nullable();
            $table->timestamps();
        });

        Schema::create('assessment_questions', function (Blueprint $table) {
            $table->id();
            $table->foreignId('assessment_id')->constrained()->cascadeOnDelete();
            $table->text('question');
            $table->json('options');           // ["A...", "B...", ...]
            $table->unsignedTinyInteger('correct_index');
            $table->string('concept')->nullable();   // sub-concept this tests
            $table->text('explanation')->nullable(); // why the correct answer is right
            $table->unsignedInteger('position')->default(0);
            $table->timestamps();
        });

        Schema::create('assessment_answers', function (Blueprint $table) {
            $table->id();
            $table->foreignId('assessment_question_id')->constrained()->cascadeOnDelete();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->unsignedTinyInteger('selected_index');
            $table->boolean('is_correct');
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('assessment_answers');
        Schema::dropIfExists('assessment_questions');
        Schema::dropIfExists('assessments');
    }
};
